### PR TITLE
Card shuffle algorithm

### PR DESCRIPTION
**Pull request by BSpoones**

### CODE REVIEW

**Comment by Jacob-Cheadle** [comment]
Jacob Cheadle - 26371737

### Improve Thoroughness of Testing
In your Testing.cs class you run all 3 shuffles consecutively without drawing any cards from the deck so it seems as if it is just one shuffle, I would suggest drawing some cards in between each shuffle to further test the strength of your code against errors. You do however display that the shuffles are running so this is a good start.

### Improving Detail of Comments
Throughout most of the classes in your program you do comment reasonably well so that someone who is quite familiar with the language and the project would be able to see what is going on however if someone was new to the language or if someone was unfamiliar with the project you were trying to code, they may struggle to see what is happening, so I would try and add a little more detail to some parts of your code.

### Missing Shuffle Function?
I'm not sure if I'm missing something here but I can't find the No Shuffle function in your code, you have done the other 2 shuffles and they appear to function correctly and be coded quite efficiently but a No Shuffle needs implementing.

Overall your code is quite concise and your commenting is moderately acceptable but I think these 3 suggestions could really improve the quality of your code.

**Comment by FawksX** [comment]
Oliver Whitehead (26435141)

**Documentation**
Generally, commenting within the program is clear and concise throughout. To improve this further, I would suggest adding header comments to public methods to assist developers who will be using this code in other projects (such as the `shuffleCardPack` method).

**Logic Error**
In your `Pack#deal` method, you are removing the card which is dealt - in the `dealCard` method you do not remove the range of cards which are taken from the top of the deck. This should be fixed to ensure that the same cards are not dealt more than once.
Other than this, the code has clear and easy to follow logic with correct error handling throughout.

**Code Suggestion**

I have two suggestions to further improve the codebase;

- Reduce repeated object instantiation if possible (for example, creating `Random` instances)
- In your `shuffleCardPack` method, you are always returning true - This should not always be the case. I would edit your method to take the `Pack` instance instead of the `List<Card>` and set the cards directly in the method (as we always only have one pack instance).

**Comment by BSpoones** [comment]
@FawksX @Jacob-Cheadle I have updated the code to meet your requirements.

**Review by FawksX — APPROVED** [review]

**Review by Jacob-Cheadle — APPROVED** [review]
All looks good

**Pull request merged**
